"""update Constraint entity_type 3

Revision ID: 038c8dc53305
Revises: c4dd1b558f15
Create Date: 2026-09-25 17:29:32.684089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '038c8dc53305'
down_revision: Union[str, None] = 'c4dd1b558f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reference_answers_ibfk_4'), 'reference_answers', type_='foreignkey')
    op.create_foreign_key(None, 'reference_answers', 'catalog_entity_type', ['entity_type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    conn = op.get_bind()
    exists = conn.execute(text("""
        SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS
        WHERE CONSTRAINT_SCHEMA = DATABASE()
          AND TABLE_NAME = 'reference_answers'
          AND CONSTRAINT_NAME = 'ck_reference_answers_exactly_one'
    """)).scalar()

    if exists:
        op.execute("ALTER TABLE reference_answers DROP CHECK ck_reference_answers_exactly_one")

    op.execute("""
        ALTER TABLE reference_answers
        ADD CONSTRAINT ck_reference_answers_exactly_one
        CHECK (
            (file_id IS NOT NULL) +
            (address_id IS NOT NULL) +
            (legal_authority_role_id IS NOT NULL) +
            (entity_type_id IS NOT NULL) = 1
        )
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference_answers', type_='foreignkey')
    op.create_foreign_key(op.f('reference_answers_ibfk_4'), 'reference_answers', 'catalog_entity_type', ['entity_type_id'], ['id'], ondelete='CASCADE')
    
    op.execute("""
        ALTER TABLE reference_answers
        ADD CONSTRAINT ck_reference_answers_exactly_one
        CHECK ((file_id IS NOT NULL) + (address_id IS NOT NULL) = 1)
    """)
    
    # ### end Alembic commands ###
    