"""fix Module references answers reference_id

Revision ID: 2123c93965df
Revises: 7a4534d4e4a7
Create Date: 2026-09-24 13:41:19.114673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2123c93965df'
down_revision: Union[str, None] = '7a4534d4e4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_field_answer_history', sa.Column('reference_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('operator_field_answer_history_ibfk_4'), 'operator_field_answer_history', type_='foreignkey')
    op.create_foreign_key(None, 'operator_field_answer_history', 'reference_answers', ['reference_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('operator_field_answer_history', 'reference__id')
    op.add_column('operator_field_answers', sa.Column('reference_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('operator_field_answers_ibfk_5'), 'operator_field_answers', type_='foreignkey')
    op.create_foreign_key(None, 'operator_field_answers', 'reference_answers', ['reference_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('operator_field_answers', 'reference__id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_field_answers', sa.Column('reference__id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operator_field_answers', type_='foreignkey')
    op.create_foreign_key(op.f('operator_field_answers_ibfk_5'), 'operator_field_answers', 'reference_answers', ['reference__id'], ['id'], ondelete='RESTRICT')
    op.drop_column('operator_field_answers', 'reference_id')
    op.add_column('operator_field_answer_history', sa.Column('reference__id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operator_field_answer_history', type_='foreignkey')
    op.create_foreign_key(op.f('operator_field_answer_history_ibfk_4'), 'operator_field_answer_history', 'reference_answers', ['reference__id'], ['id'], ondelete='RESTRICT')
    op.drop_column('operator_field_answer_history', 'reference_id')
    # ### end Alembic commands ###