"""catalog business_activity

Revision ID: 4af6a8c6149c
Revises: 038c8dc53305
Create Date: 2026-09-25 18:00:41.827998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '4af6a8c6149c'
down_revision: Union[str, None] = '038c8dc53305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_business_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reference_answers', sa.Column('business_activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reference_answers', 'catalog_business_activity', ['business_activity_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    conn = op.get_bind()
    exists = conn.execute(text("""
            SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS
            WHERE CONSTRAINT_SCHEMA = DATABASE()
              AND TABLE_NAME = 'reference_answers'
              AND CONSTRAINT_NAME = 'ck_reference_answers_exactly_one'
        """)).scalar()
    
    if exists:
        op.execute("ALTER TABLE reference_answers DROP CHECK ck_reference_answers_exactly_one")
    
        op.execute("""
            ALTER TABLE reference_answers
            ADD CONSTRAINT ck_reference_answers_exactly_one
            CHECK (
                (file_id IS NOT NULL) +
                (address_id IS NOT NULL) +
                (legal_authority_role_id IS NOT NULL) +
                (entity_type_id IS NOT NULL) = 1
            )
        """)




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference_answers', type_='foreignkey')
    op.drop_column('reference_answers', 'business_activity_id')
    op.drop_table('catalog_business_activity')
    # ### end Alembic commands ###
    
    op.execute("""
            ALTER TABLE reference_answers
            ADD CONSTRAINT ck_reference_answers_exactly_one
            CHECK ((file_id IS NOT NULL) + (address_id IS NOT NULL) = 1)
        """)
        