"""add update name catalog_entity_type

Revision ID: 6d3ca3b7dbc8
Revises: da0480b9fd32
Create Date: 2026-09-25 16:06:18.783748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3ca3b7dbc8'
down_revision: Union[str, None] = 'da0480b9fd32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###