"""fix Module references answers

Revision ID: 7a4534d4e4a7
Revises: ce9af581b184
Create Date: 2026-09-23 17:53:25.452608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a4534d4e4a7'
down_revision: Union[str, None] = 'ce9af581b184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_field_answers', sa.Column('reference__id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('operator_field_answers_ibfk_2'), 'operator_field_answers', type_='foreignkey')
    op.drop_constraint(op.f('operator_field_answers_ibfk_1'), 'operator_field_answers', type_='foreignkey')
    op.create_foreign_key(None, 'operator_field_answers', 'reference_answers', ['reference__id'], ['id'], ondelete='RESTRICT')
    op.drop_column('operator_field_answers', 'address_id')
    op.drop_column('operator_field_answers', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_field_answers', sa.Column('file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('operator_field_answers', sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operator_field_answers', type_='foreignkey')
    op.create_foreign_key(op.f('operator_field_answers_ibfk_1'), 'operator_field_answers', 'operators_addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('operator_field_answers_ibfk_2'), 'operator_field_answers', 'operators_files', ['file_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('operator_field_answers', 'reference__id')
    # ### end Alembic commands ###