"""operator_type key

Revision ID: 81430cff7dd7
Revises: 948b199a6263
Create Date: 2026-09-17 22:01:41.354624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81430cff7dd7'
down_revision: Union[str, None] = '948b199a6263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_operators_type', sa.Column('key', sa.String(length=5), nullable=False))
    op.drop_column('operators', 'website')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('website', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('catalog_operators_type', 'key')
    # ### end Alembic commands ###