"""table operators_files && catalog_types_files

Revision ID: 904d8aa57fd2
Revises: ce09ae571b91
Create Date: 2026-09-18 10:58:31.902049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904d8aa57fd2'
down_revision: Union[str, None] = 'ce09ae571b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_types_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('type_file_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_file_id'], ['catalog_types_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_files_operator_id'), 'operators_files', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operators_files_type_file_id'), 'operators_files', ['type_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operators_files_type_file_id'), table_name='operators_files')
    op.drop_index(op.f('ix_operators_files_operator_id'), table_name='operators_files')
    op.drop_table('operators_files')
    op.drop_table('catalog_types_files')
    # ### end Alembic commands ###