"""operators tables

Revision ID: 948b199a6263
Revises: fabaef52be06
Create Date: 2026-09-14 16:58:14.409699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948b199a6263'
down_revision: Union[str, None] = 'fabaef52be06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_operators_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_operators_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_operators_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mo', sa.String(length=50), nullable=True),
    sa.Column('operator_status_id', sa.Integer(), nullable=True),
    sa.Column('operator_type_id', sa.Integer(), nullable=True),
    sa.Column('operator_class_id', sa.Integer(), nullable=True),
    sa.Column('trade_name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('rfc_tax_id', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('email_fiscal_contact', sa.String(length=100), nullable=True),
    sa.Column('cedula_fiscal_name', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('code_num', sa.String(length=45), nullable=True),
    sa.Column('code_alfa', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_class_id'], ['catalog_operators_class.id'], ),
    sa.ForeignKeyConstraint(['operator_status_id'], ['catalog_operators_statuses.id'], ),
    sa.ForeignKeyConstraint(['operator_type_id'], ['catalog_operators_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_operators_operator_class_id'), 'operators', ['operator_class_id'], unique=False)
    op.create_index(op.f('ix_operators_operator_status_id'), 'operators', ['operator_status_id'], unique=False)
    op.create_index(op.f('ix_operators_operator_type_id'), 'operators', ['operator_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operators_operator_type_id'), table_name='operators')
    op.drop_index(op.f('ix_operators_operator_status_id'), table_name='operators')
    op.drop_index(op.f('ix_operators_operator_class_id'), table_name='operators')
    op.drop_table('operators')
    op.drop_table('catalog_operators_type')
    op.drop_table('catalog_operators_statuses')
    op.drop_table('catalog_operators_class')
    # ### end Alembic commands ###