"""add key in table catalog_types_files

Revision ID: 961d06d51bc3
Revises: 904d8aa57fd2
Create Date: 2026-09-18 11:06:31.733314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961d06d51bc3'
down_revision: Union[str, None] = '904d8aa57fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###