"""fix evaluated_at is Nullable

Revision ID: ad4df519001e
Revises: d40fe4d13875
Create Date: 2026-09-21 17:18:31.429310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad4df519001e'
down_revision: Union[str, None] = 'd40fe4d13875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operator_field_answers', 'evaluated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operator_field_answers', 'evaluated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###