"""update Constraint entity_type 2

Revision ID: c4dd1b558f15
Revises: 93ca7c728c1a
Create Date: 2026-09-25 17:29:08.717630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4dd1b558f15'
down_revision: Union[str, None] = '93ca7c728c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reference_answers_ibfk_4'), 'reference_answers', type_='foreignkey')
    op.create_foreign_key(None, 'reference_answers', 'catalog_entity_type', ['entity_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference_answers', type_='foreignkey')
    op.create_foreign_key(op.f('reference_answers_ibfk_4'), 'reference_answers', 'catalog_entity_type', ['entity_type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###