"""fix name catalog_operator_field_answer_history

Revision ID: c8d6471f9f0f
Revises: 9095ca066d0d
Create Date: 2026-09-23 17:20:12.191430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8d6471f9f0f'
down_revision: Union[str, None] = '9095ca066d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_legal_title_authority_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_field_answer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_field_answer_id', sa.Integer(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('validation_state', sa.String(length=20), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('evaluated_by', sa.String(length=100), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['operators_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['operators_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_field_answer_id'], ['operator_field_answers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_field_answer_history_recorded_at'), 'operator_field_answer_history', ['recorded_at'], unique=False)
    op.drop_table('legal_title_authority_role')
    op.drop_index(op.f('ix_catalog_operator_field_answer_history_recorded_at'), table_name='catalog_operator_field_answer_history')
    op.drop_table('catalog_operator_field_answer_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_operator_field_answer_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_field_answer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_text', mysql.TEXT(), nullable=True),
    sa.Column('file_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('validation_state', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('observations', mysql.TEXT(), nullable=True),
    sa.Column('evaluated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('evaluated_at', mysql.DATETIME(), nullable=True),
    sa.Column('recorded_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['operators_addresses.id'], name=op.f('catalog_operator_field_answer_history_ibfk_1'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['operators_files.id'], name=op.f('catalog_operator_field_answer_history_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_field_answer_id'], ['operator_field_answers.id'], name=op.f('catalog_operator_field_answer_history_ibfk_3'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_catalog_operator_field_answer_history_recorded_at'), 'catalog_operator_field_answer_history', ['recorded_at'], unique=False)
    op.create_table('legal_title_authority_role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_operator_field_answer_history_recorded_at'), table_name='operator_field_answer_history')
    op.drop_table('operator_field_answer_history')
    op.drop_table('catalog_legal_title_authority_role')
    # ### end Alembic commands ###