"""table operators_users

Revision ID: ce09ae571b91
Revises: efb49d983ac5
Create Date: 2026-09-17 23:48:21.331997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce09ae571b91'
down_revision: Union[str, None] = 'efb49d983ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_operators_users_user_id')
    )
    op.create_index(op.f('ix_operators_users_operator_id'), 'operators_users', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operators_users_user_id'), 'operators_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operators_users_user_id'), table_name='operators_users')
    op.drop_index(op.f('ix_operators_users_operator_id'), table_name='operators_users')
    op.drop_table('operators_users')
    # ### end Alembic commands ###