"""Module references answers

Revision ID: ce9af581b184
Revises: c8d6471f9f0f
Create Date: 2026-09-23 17:51:54.815335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce9af581b184'
down_revision: Union[str, None] = 'c8d6471f9f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('legal_authority_role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('CASE WHEN (file_id IS NOT NULL) THEN 1 ELSE 0 END + CASE WHEN (address_id IS NOT NULL) THEN 1 ELSE 0 END + CASE WHEN (legal_authority_role_id IS NOT NULL) THEN 1 ELSE 0 END = 1', name='ck_reference_answers_exactly_one'),
    sa.ForeignKeyConstraint(['address_id'], ['operators_addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file_id'], ['operators_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['legal_authority_role_id'], ['catalog_legal_title_authority_role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('operator_field_answer_history', sa.Column('reference__id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('operator_field_answer_history_ibfk_2'), 'operator_field_answer_history', type_='foreignkey')
    op.drop_constraint(op.f('operator_field_answer_history_ibfk_1'), 'operator_field_answer_history', type_='foreignkey')
    op.create_foreign_key(None, 'operator_field_answer_history', 'reference_answers', ['reference__id'], ['id'], ondelete='RESTRICT')
    op.drop_column('operator_field_answer_history', 'file_id')
    op.drop_column('operator_field_answer_history', 'address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_field_answer_history', sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('operator_field_answer_history', sa.Column('file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operator_field_answer_history', type_='foreignkey')
    op.create_foreign_key(op.f('operator_field_answer_history_ibfk_1'), 'operator_field_answer_history', 'operators_addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('operator_field_answer_history_ibfk_2'), 'operator_field_answer_history', 'operators_files', ['file_id'], ['id'], ondelete='SET NULL')
    op.drop_column('operator_field_answer_history', 'reference__id')
    op.drop_table('reference_answers')
    # ### end Alembic commands ###