"""group_id None

Revision ID: d1d0d61db5a9
Revises: b57ced82276f
Create Date: 2026-09-10 19:45:58.932206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1d0d61db5a9'
down_revision: Union[str, None] = 'b57ced82276f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###