"""fix tables section && modules ecosystem

Revision ID: d3d62807e500
Revises: 35392755ed9e
Create Date: 2026-09-20 13:58:54.661992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d62807e500'
down_revision: Union[str, None] = '35392755ed9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_addresses_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_status_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('result_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_status_rules_module_id'), 'module_status_rules', ['module_id'], unique=False)
    op.create_table('operators_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('address_type_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('ext_number', sa.String(length=20), nullable=False),
    sa.Column('int_number', sa.String(length=20), nullable=False),
    sa.Column('neighborhood', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=150), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['address_type_id'], ['catalog_addresses_types.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_addresses_address_type_id'), 'operators_addresses', ['address_type_id'], unique=False)
    op.create_index(op.f('ix_operators_addresses_operator_id'), 'operators_addresses', ['operator_id'], unique=False)
    op.create_table('section_field_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'code', name='uq_section_field_code')
    )
    op.create_index(op.f('ix_section_field_rules_section_id'), 'section_field_rules', ['section_id'], unique=False)
    op.create_table('section_status_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=False),
    sa.Column('result_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_status_rules_section_id'), 'section_status_rules', ['section_id'], unique=False)
    op.create_table('operator_field_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('section_field_rule_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('validation_state', sa.String(length=20), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('evaluated_by', sa.String(length=100), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['operators_addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file_id'], ['operators_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_field_rule_id'], ['section_field_rules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'section_field_rule_id', name='uq_operator_field')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operator_field_answers')
    op.drop_index(op.f('ix_section_status_rules_section_id'), table_name='section_status_rules')
    op.drop_table('section_status_rules')
    op.drop_index(op.f('ix_section_field_rules_section_id'), table_name='section_field_rules')
    op.drop_table('section_field_rules')
    op.drop_index(op.f('ix_operators_addresses_operator_id'), table_name='operators_addresses')
    op.drop_index(op.f('ix_operators_addresses_address_type_id'), table_name='operators_addresses')
    op.drop_table('operators_addresses')
    op.drop_index(op.f('ix_module_status_rules_module_id'), table_name='module_status_rules')
    op.drop_table('module_status_rules')
    op.drop_table('catalog_addresses_types')
    # ### end Alembic commands ###