"""add code in ModuleModel && SectionsModel

Revision ID: d40fe4d13875
Revises: ef6dff7fe4d1
Create Date: 2026-09-21 11:25:36.722194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40fe4d13875'
down_revision: Union[str, None] = 'ef6dff7fe4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('code', sa.Text(), nullable=False))
    op.add_column('sections', sa.Column('code', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'code')
    op.drop_column('modules', 'code')
    # ### end Alembic commands ###