"""add entity_type in reference

Revision ID: e473003b9136
Revises: 6d3ca3b7dbc8
Create Date: 2026-09-25 17:07:58.434049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e473003b9136'
down_revision: Union[str, None] = '6d3ca3b7dbc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_answers', sa.Column('entity_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reference_answers', 'catalog_entity_type', ['entity_type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference_answers', type_='foreignkey')
    op.drop_column('reference_answers', 'entity_type_id')
    # ### end Alembic commands ###