"""add condition_name in ModuleStatusRuleModel

Revision ID: ef6dff7fe4d1
Revises: d3d62807e500
Create Date: 2026-09-21 11:11:39.103271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6dff7fe4d1'
down_revision: Union[str, None] = 'd3d62807e500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_field_answer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_field_answer_id', sa.Integer(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('validation_state', sa.String(length=20), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('evaluated_by', sa.String(length=100), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['operators_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['operators_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_field_answer_id'], ['operator_field_answers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_field_answer_history_recorded_at'), 'operator_field_answer_history', ['recorded_at'], unique=False)
    op.add_column('module_status_rules', sa.Column('condition_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_status_rules', 'condition_name')
    op.drop_index(op.f('ix_operator_field_answer_history_recorded_at'), table_name='operator_field_answer_history')
    op.drop_table('operator_field_answer_history')
    # ### end Alembic commands ###