"""fix add key in table catalog_types_files

Revision ID: f4e9f05d1a3c
Revises: 961d06d51bc3
Create Date: 2026-09-18 11:07:45.838559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e9f05d1a3c'
down_revision: Union[str, None] = '961d06d51bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_types_files', sa.Column('key', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_types_files', 'key')
    # ### end Alembic commands ###