"""update_catalogs_operators

Revision ID: f7c9fead65c4
Revises: 81430cff7dd7
Create Date: 2026-09-17 22:06:19.494134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7c9fead65c4'
down_revision: Union[str, None] = '81430cff7dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_operators_class', sa.Column('key', sa.String(length=5), nullable=True))
    op.drop_column('catalog_operators_class', 'created_at')
    op.drop_column('catalog_operators_class', 'updated_at')
    op.drop_column('catalog_operators_statuses', 'created_at')
    op.drop_column('catalog_operators_statuses', 'updated_at')
    op.drop_column('catalog_operators_type', 'created_at')
    op.drop_column('catalog_operators_type', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_operators_type', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('catalog_operators_type', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('catalog_operators_statuses', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('catalog_operators_statuses', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('catalog_operators_class', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('catalog_operators_class', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('catalog_operators_class', 'key')
    # ### end Alembic commands ###