"""patch table users

Revision ID: fabaef52be06
Revises: d1d0d61db5a9
Create Date: 2026-09-10 19:48:06.028342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fabaef52be06'
down_revision: Union[str, None] = 'd1d0d61db5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'second_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'second_last_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'second_last_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('users', 'second_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###